proxmox_node = "pve1"
proxmox_url = "https://192.168.1.104:8006/api2/json"
proxmox_storage_pool = "local"
proxmox_token = "************************8"
proxmox_username = "root@pam!packer"
proxmox_iso_pool = "pve-backups:iso"
network_bridge = "vmbr0"